# Generated by Django 5.2.8 on 2025-12-20 07:51

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerSaleInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sale_number', models.CharField(max_length=50, unique=True)),
                ('sale_date', models.DateField()),
                ('customer_name', models.CharField(max_length=100)),
                ('customer_contact', models.CharField(blank=True, max_length=20, null=True)),
                ('total_quantity', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('cash_received', models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('cash_return', models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
            ],
            options={
                'ordering': ['-sale_date'],
            },
        ),
        migrations.CreateModel(
            name='ItemStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(max_length=50)),
                ('vender_code', models.CharField(max_length=50)),
                ('item_code', models.CharField(default='', max_length=50)),
                ('product_name', models.CharField(max_length=100)),
                ('company_name', models.CharField(max_length=100)),
                ('specification', models.CharField(blank=True, max_length=255, null=True)),
                ('barcode_number', models.CharField(max_length=50)),
                ('total_qty', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('sale_rate', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('rate', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('expire_date', models.DateField(blank=True, null=True)),
                ('sale_qty', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('sale_return_qty', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('stock_return_qty', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('available_qty', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
            ],
        ),
        migrations.CreateModel(
            name='SaleInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sale_number', models.CharField(max_length=50, unique=True)),
                ('sale_date', models.DateField()),
                ('customer_name', models.CharField(max_length=100)),
                ('customer_contact', models.CharField(blank=True, max_length=20, null=True)),
                ('total_quantity', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('cash_received', models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('cash_return', models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
            ],
        ),
        migrations.CreateModel(
            name='SaleReturn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('barcode_number', models.CharField(default='', max_length=50, unique=True)),
                ('description', models.CharField(default='', max_length=255)),
                ('specification', models.CharField(blank=True, max_length=255, null=True)),
                ('qty', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(0)])),
                ('sale_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('total_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
            ],
        ),
        migrations.CreateModel(
            name='SaleReturnDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sale_number', models.CharField(default='', max_length=50, unique=True)),
                ('sale_date', models.DateField(blank=True, null=True)),
                ('customer_name', models.CharField(default='', max_length=100)),
                ('customer_contact', models.CharField(blank=True, max_length=20, null=True)),
                ('return_number', models.CharField(default='', max_length=50, unique=True)),
                ('return_date', models.DateField(blank=True, null=True)),
                ('total_quantity', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('total_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('amount_refunded', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('reason_for_return', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='StockAssigned',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_code', models.CharField(max_length=50, unique=True)),
                ('product_name', models.CharField(max_length=100)),
                ('company_name', models.CharField(max_length=100)),
                ('specification', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'ordering': ['item_code'],
            },
        ),
        migrations.CreateModel(
            name='stockreceving',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(max_length=50)),
                ('order_date', models.DateField()),
                ('vender_code', models.CharField(max_length=50)),
                ('vendor_name', models.CharField(max_length=100)),
                ('total_qty', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
            ],
        ),
        migrations.CreateModel(
            name='VenderDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vender_code', models.CharField(max_length=50, unique=True)),
                ('vender_name', models.CharField(max_length=100)),
                ('vender_number', models.CharField(blank=True, max_length=20, null=True)),
                ('company_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ExchangeSale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exchange_number', models.CharField(max_length=50, unique=True)),
                ('exchange_date', models.DateField()),
                ('total_qty', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('refund_amount', models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('cash_received', models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('cash_return', models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('sale_invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exchange_sales', to='core.customersaleinvoice')),
                ('return_invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='exchange_sales', to='core.salereturn')),
            ],
        ),
        migrations.CreateModel(
            name='SaleDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('barcode_number', models.CharField(max_length=50, unique=True)),
                ('item_code', models.CharField(max_length=50)),
                ('product_name', models.CharField(max_length=100)),
                ('company_name', models.CharField(max_length=100)),
                ('specification', models.CharField(blank=True, max_length=255, null=True)),
                ('qty', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(0)])),
                ('sale_rate', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('sale', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='details', to='core.saleinfo')),
            ],
        ),
        migrations.CreateModel(
            name='ExchangeSaleDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('barcode_number', models.CharField(max_length=50)),
                ('qty', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('exchange_sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='core.exchangesale')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='exchange_sale_details', to='core.stockassigned')),
            ],
        ),
        migrations.CreateModel(
            name='StockReceivingDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(max_length=50)),
                ('order_date', models.DateField()),
                ('barcode_number', models.CharField(max_length=50, unique=True)),
                ('qty', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('rate', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('sale_rate', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('expire_date', models.DateField(blank=True, null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='receivings', to='core.stockassigned')),
                ('vender', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='receivings', to='core.venderdetails')),
            ],
            options={
                'indexes': [models.Index(fields=['order_number'], name='core_stockr_order_n_11d4c5_idx'), models.Index(fields=['barcode_number'], name='core_stockr_barcode_37417b_idx')],
            },
        ),
    ]
