# Generated by Django 5.2.8 on 2025-12-20 08:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saledetail',
            name='barcode_number',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='saledetail',
            name='sale',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='core.saleinfo'),
        ),
    ]
