# Generated by Django 5.2.8 on 2025-12-20 09:54

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_saledetail_barcode_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='salereturn',
            name='return_detail',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='items', to='core.salereturndetail'),
        ),
        migrations.AlterField(
            model_name='salereturn',
            name='barcode_number',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='salereturn',
            name='description',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='salereturn',
            name='qty',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='salereturn',
            name='sale_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AlterField(
            model_name='salereturn',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AlterField(
            model_name='salereturndetail',
            name='amount_refunded',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14),
        ),
        migrations.AlterField(
            model_name='salereturndetail',
            name='return_number',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='salereturndetail',
            name='sale_number',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='salereturndetail',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14),
        ),
        migrations.AlterField(
            model_name='salereturndetail',
            name='total_quantity',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
