# Generated by Django 5.2.8 on 2025-12-20 10:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_salereturn_return_detail_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salereturn',
            name='return_detail',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='core.salereturndetail'),
        ),
    ]
